### PR TITLE
added ord and yojson ppx derivers to most major types

### PR DESCRIPTION
**Pull request by jcm-cryptosense**

### CODE REVIEW

**Comment by NathanReb** [comment]
Could you please do the same for the `Ltpa` module ?

**Comment by NathanReb** [comment]
And update `CHANGELOG.md` ;)

**Comment by jcm-cryptosense** [comment]
Which section of the change log should I document the changes in? `unreleased`?

**Comment by jcm-cryptosense** [comment]
`CHANGELOG.md` updated and compilation fixed. :tada:

**Pull request merged**
